language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ekady/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true ekady/react-test npm run test

after_success: 
  - docker build -t ekady/multi-client ./client
  - docker build -t ekady/multi-nginx ./nginx
  - docker build -t ekady/multi-worker ./worker
  - docker build -t ekady/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ekady/multi-client
  - docker push ekady/multi-nginx
  - docker push ekady/multi-worker
  - docker push ekady/multi-server

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: Multi-docker-env
  bucket_name: 	$AWS_BUCKET_NAME
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
